name: Keep Server Awake

on:
  schedule:
    - cron: '*/1 * * * *'  # 매 1분마다 실행

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      TARGET_URL: "https://discord-bot-hello.onrender.com"
    steps:
      - name: Send GET request
        run: curl --retry 3 --retry-delay 5 -X GET "$TARGET_URL"